name: tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install softwares
      run: choco install 7zip.install

    - name: Configure
      run: cmake -Bbuild -T host=x64 -A x64

    - name: Build
      run: cmake --build build --config Debug -j4

    - name: Download Mesa
      run: cd build\Debug && curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/20.3.2/mesa3d-20.3.2-release-msvc.7z

    - name: Extract Mesa
      run: cd build\Debug && \"C:\Program Files\7-Zip\7z.exe\" x mesa.7z

    - name: Symlink Mesa
      run: cd build\Debug && && mklink opengl32.dll \"x64\opengl32.dll\" && mklink libglapi.dll \"x64\libglapi.dll\"

    - name: Run tests
      shell: cmd
      run: call "build\Debug\TestGL.exe"
